[project]
name = "agent"
version = "0.1.0"
description = "Yet another agent harness"
requires-python = ">=3.12"
dependencies = [
    "openai",
    "openai-agents",
    "jinja2",
    "omegaconf",
    "websockets",
    "cachetools",
    "transformers @ git+https://github.com/huggingface/transformers",
    "accelerate",
    "pillow",
    "lighteval"
]

[project.optional-dependencies]
e2e = ["playwright"]

[project.scripts]
agent = "agent:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
include = ["agent.py", "agent_ui.html", "agent_ui.css", "agent_ui.js"]
