[project]
name = "agent"
version = "0.1.0"
description = "An application agnostic agent harness library"
requires-python = ">=3.12"
dependencies = [
    "openai",
    "openai-agents",
    "jinja2",
    "websockets",
    "cachetools",
    "git+https://github.com/huggingface/transformers",
    "accelerate",
    "pillow"
]

[project.scripts]
agent = "agent:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = ["agent.py", "agent_ui.html", "agent_ui.css", "agent_ui.js"]
